<a href="https://colab.research.google.com/github/Truman7777/M1/blob/main/M1%EA%B3%B5%EB%B6%80_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy

In [ ]:
import numpy as np

In [ ]:
list = [1, 5, 8]
print(list * 3)

[1, 5, 8, 1, 5, 8, 1, 5, 8]


In [ ]:
arr = np.array(list)
print(arr * 3)
print(arr + 100)

[ 3 15 24]
[101 105 108]


In [ ]:
data = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
print(data)
print(type(data))

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
<class 'list'>


In [ ]:
arr2 = np.array(data) # 리스트를 ndarray로 변환
print(arr2)
print(type(arr2))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>


In [ ]:
# 배열 인덱싱
print(arr2[1, 2])
print(arr2[1][2])

6
6


In [ ]:
print(arr2[0])
print(arr2[1])
print(arr2[2])

[1 2 3]
[4 5 6]
[7 8 9]


In [ ]:
#배열 슬라이싱
print(arr2[:2, 1:])

[[2 3]
 [5 6]]


In [ ]:
# arange
data = np.arange(12).reshape(4, 3) # arange -> range와 같지만 arry형태로 숫자 만듦
data # reshape -> 배열의 차원을 생성, 변경할 때 사용 

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
data[data<6] = 0 # data<6 결과 True or False로 구성된 2차원 배열 얻음
data # 결과적으로 True 부분만 0으로 대체된 새로운 배열 얻음

array([[ 0,  0,  0],
       [ 0,  0,  0],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
data<6

array([[ True,  True,  True],
       [ True,  True,  True],
       [False, False, False],
       [False, False, False]])

In [ ]:
data.mean() # mean() -> 평균을 구할 때 사용

4.25

In [ ]:
data.mean(axis=0) # axis=0 -> 각 행의 같은 위치 항목들끼리의 계산

array([3.75, 4.25, 4.75])

In [ ]:
data.mean(axis=1) # axis=1 -> 각 열의 같은 위치 항목들끼리의 계산

array([ 0.,  0.,  7., 10.])