<a href="https://colab.research.google.com/github/Truman7777/M1/blob/main/%EC%95%BC%EA%B0%84%EB%8C%80%ED%95%991.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
X = [[5.1, 3.5, 1.4], [4.9, 3.0, 1.4],
     [4.7, 3.2, 1.3], [4.6, 3.1, 1.5], [5.0, 3.6, 1.4]]

y = [0.2, 0.4, 0.3, 0.2, 0.3]

In [3]:
X

[[5.1, 3.5, 1.4],
 [4.9, 3.0, 1.4],
 [4.7, 3.2, 1.3],
 [4.6, 3.1, 1.5],
 [5.0, 3.6, 1.4]]

In [4]:
y

[0.2, 0.4, 0.3, 0.2, 0.3]

In [5]:
XX = np.array(X)
XX

array([[5.1, 3.5, 1.4],
       [4.9, 3. , 1.4],
       [4.7, 3.2, 1.3],
       [4.6, 3.1, 1.5],
       [5. , 3.6, 1.4]])

In [6]:
yy = np.array(y)
yy

array([0.2, 0.4, 0.3, 0.2, 0.3])

In [7]:
w1 = 1.0
w2 = 1.0
w3 = 1.0
b = 1.0
# 가중치 값 일단 넣어줌

In [8]:
W = np.array([1.0, 1.0, 1.0])
b = 1.0

In [15]:
result_y = X@W + b
result_y

array([11. , 10.3, 10.2, 10.2, 11. ])

In [17]:
(XX * W).sum(axis= 1) + b

array([11. , 10.3, 10.2, 10.2, 11. ])

In [18]:
C = (result_y - yy) ** 2
C

array([116.64,  98.01,  98.01, 100.  , 114.49])

In [24]:
MSE = ((result_y - y)**2).mean()
MSE

105.42999999999999